from pathlib import Path

path = Path("crates/mimir-io/src/lib.rs")
text = path.read_text(encoding="utf-8")

old_write = """pub fn write_scoreboard_artifact(\n    path: impl AsRef<Path>,\n    format: ArtifactFormat,\n    artifact: &PersistedScoreboardArtifact,\n) -> Result<()> {\n    write_artifact(path, format, artifact)\n}\n"""
new_write = """pub fn write_scoreboard_artifact(\n    path: impl AsRef<Path>,\n    format: ArtifactFormat,\n    artifact: &PersistedScoreboardArtifact,\n) -> Result<()> {\n    validate_scoreboard_payload(&artifact.payload)?;\n    write_artifact(path, format, artifact)\n}\n"""
if text.count(old_write) != 1:
    raise SystemExit(f"scoreboard write anchor drift: expected 1, got {text.count(old_write)}")
text = text.replace(old_write, new_write, 1)

old_read = """pub fn read_scoreboard_artifact(path: impl AsRef<Path>) -> Result<PersistedScoreboardArtifact> {\n    read_artifact_auto(path, SCOREBOARD_ARTIFACT_SCHEMA)\n}\n"""
new_read = """pub fn read_scoreboard_artifact(path: impl AsRef<Path>) -> Result<PersistedScoreboardArtifact> {\n    let artifact: PersistedScoreboardArtifact = read_artifact_auto(path, SCOREBOARD_ARTIFACT_SCHEMA)?;\n    validate_scoreboard_payload(&artifact.payload)?;\n    Ok(artifact)\n}\n\nfn validate_scoreboard_payload(scoreboard: &PersistedScoreboard) -> Result<()> {\n    for (row_index, row) in scoreboard.rows.iter().enumerate() {\n        match row.score.branch_id.as_ref() {\n            Some(score_branch_id) if score_branch_id == &row.branch_id => {}\n            Some(score_branch_id) => {\n                return Err(MimirError::message(format!(\n                    \"scoreboard row {row_index} branch id mismatch: row has {}, score has {}\",\n                    row.branch_id, score_branch_id\n                )));\n            }\n            None => {\n                return Err(MimirError::message(format!(\n                    \"scoreboard row {row_index} score is missing branch id for {}\",\n                    row.branch_id\n                )));\n            }\n        }\n    }\n\n    Ok(())\n}\n"""
if text.count(old_read) != 1:
    raise SystemExit(f"scoreboard read anchor drift: expected 1, got {text.count(old_read)}")
text = text.replace(old_read, new_read, 1)

marker = """    #[test]\n    fn scoreboard_wrapper_rejects_schema_mismatch_explicitly() {\n"""
tests = """    #[test]\n    fn scoreboard_wrapper_rejects_nested_branch_id_mismatch_before_write() {\n        let directory = tempdir().expect(\"tempdir should be created\");\n        let path = scoreboard_artifact_path(directory.path());\n        let artifact = PersistedScoreboardArtifact::new(\n            ArtifactHeader::for_kind(ArtifactKind::Scoreboard, \"mimir-io-tests\"),\n            PersistedScoreboard {\n                rows: vec![PersistedScoreRow {\n                    branch_id: BranchId::new(\"branch-a\"),\n                    branch_label: None,\n                    simulation_id: \"sim-1\".to_string(),\n                    simulation_backend: \"deterministic_fake\".to_string(),\n                    step_hashes: vec![\"step-a\".to_string()],\n                    score: PersistedScoreVector {\n                        branch_id: Some(BranchId::new(\"branch-b\")),\n                        components: BTreeMap::new(),\n                        total: 0.0,\n                    },\n                }],\n            },\n        );\n\n        let error = write_scoreboard_artifact(&path, ArtifactFormat::Json, &artifact)\n            .expect_err(\"mismatched nested branch identity must fail before write\");\n\n        assert!(error.to_string().contains(\"scoreboard row 0 branch id mismatch\"));\n        assert!(!path.exists());\n    }\n\n    #[test]\n    fn scoreboard_loader_rejects_missing_nested_branch_id_from_generic_write() {\n        let directory = tempdir().expect(\"tempdir should be created\");\n        let path = scoreboard_artifact_path(directory.path());\n        let artifact = PersistedScoreboardArtifact::new(\n            ArtifactHeader::for_kind(ArtifactKind::Scoreboard, \"mimir-io-tests\"),\n            PersistedScoreboard {\n                rows: vec![PersistedScoreRow {\n                    branch_id: BranchId::new(\"branch-a\"),\n                    branch_label: None,\n                    simulation_id: \"sim-1\".to_string(),\n                    simulation_backend: \"deterministic_fake\".to_string(),\n                    step_hashes: vec![\"step-a\".to_string()],\n                    score: PersistedScoreVector {\n                        branch_id: None,\n                        components: BTreeMap::new(),\n                        total: 0.0,\n                    },\n                }],\n            },\n        );\n\n        write_artifact(&path, ArtifactFormat::Json, &artifact)\n            .expect(\"generic artifact write should bypass scoreboard semantic validation\");\n        let error = read_scoreboard_artifact(&path)\n            .expect_err(\"scoreboard loader must reject missing nested branch identity\");\n\n        assert!(\n            error\n                .to_string()\n                .contains(\"scoreboard row 0 score is missing branch id for branch-a\")\n        );\n    }\n\n"""
if text.count(marker) != 1:
    raise SystemExit(f"scoreboard test insertion anchor drift: expected 1, got {text.count(marker)}")
text = text.replace(marker, tests + marker, 1)

path.write_text(text, encoding="utf-8", newline="\n")
print("AUX_SCOREBOARD_BRANCH_BINDING_PATCH=PASS")
