from pathlib import Path

path = Path("crates/mimir-io/src/lib.rs")
text = path.read_text(encoding="utf-8")

old_import = "use std::fs;\nuse std::path::{Path, PathBuf};\n"
new_import = "use std::fs;\nuse std::io::Write;\nuse std::path::{Path, PathBuf};\nuse std::sync::atomic::{AtomicU64, Ordering};\n"
if text.count(old_import) != 1:
    raise SystemExit("mimir-io import marker drift")
text = text.replace(old_import, new_import, 1)

old_write = '''    fs::write(path, text).map_err(|error| MimirError::io(path, error))\n}\n'''
new_write = '''    write_text_file_staged(path, &text)\n}\n\nstatic ARTIFACT_STAGE_NONCE: AtomicU64 = AtomicU64::new(0);\n\nfn write_text_file_staged(path: &Path, text: &str) -> Result<()> {\n    let parent = path.parent().unwrap_or_else(|| Path::new("."));\n    let file_name = path.file_name().ok_or_else(|| {\n        MimirError::message(format!("artifact path has no file name: {}", path.display()))\n    })?;\n\n    let mut stage = None;\n    for _ in 0..128 {\n        let nonce = ARTIFACT_STAGE_NONCE.fetch_add(1, Ordering::Relaxed);\n        let candidate = parent.join(format!(\n            ".{}.mimir-stage-{}-{nonce}",\n            file_name.to_string_lossy(),\n            std::process::id()\n        ));\n        match fs::OpenOptions::new()\n            .write(true)\n            .create_new(true)\n            .open(&candidate)\n        {\n            Ok(file) => {\n                stage = Some((candidate, file));\n                break;\n            }\n            Err(error) if error.kind() == std::io::ErrorKind::AlreadyExists => continue,\n            Err(error) => return Err(MimirError::io(&candidate, error)),\n        }\n    }\n\n    let (stage_path, mut stage_file) = stage.ok_or_else(|| {\n        MimirError::message(format!(\n            "could not allocate unique staged artifact file for {}",\n            path.display()\n        ))\n    })?;\n\n    if let Err(error) = stage_file.write_all(text.as_bytes()) {\n        drop(stage_file);\n        let _ = fs::remove_file(&stage_path);\n        return Err(MimirError::io(&stage_path, error));\n    }\n    if let Err(error) = stage_file.flush() {\n        drop(stage_file);\n        let _ = fs::remove_file(&stage_path);\n        return Err(MimirError::io(&stage_path, error));\n    }\n    drop(stage_file);\n\n    if let Err(error) = fs::rename(&stage_path, path) {\n        let _ = fs::remove_file(&stage_path);\n        return Err(MimirError::io(path, error));\n    }\n\n    Ok(())\n}\n'''
if text.count(old_write) != 1:
    raise SystemExit(f"expected one generic artifact fs::write block, found {text.count(old_write)}")
text = text.replace(old_write, new_write, 1)

marker = '''    #[test]\n    fn rejects_unsupported_schema_versions() {\n'''
if text.count(marker) != 1:
    raise SystemExit("test insertion marker drift")
tests = '''    #[test]\n    fn generic_artifact_writer_replaces_via_staged_file_without_leftovers() {\n        let directory = tempdir().expect("tempdir should be created");\n        let path = directory.path().join("artifact.json");\n        fs::write(&path, b"legacy-bytes").expect("seed destination");\n\n        let artifact = PersistedAnchorArtifact::new(\n            ArtifactHeader::for_kind(ArtifactKind::Anchor, "mimir-io-staged-write-test"),\n            AnchorArtifactPayload {\n                id: AnchorId::new("anchor-staged-write"),\n                replay_id: ReplayId::new("replay-staged-write"),\n                frame_index: FrameIndex::new(7),\n                kind: AnchorKind::Manual,\n                metadata: Metadata::new(),\n            },\n        );\n\n        write_artifact(&path, ArtifactFormat::Json, &artifact).expect("staged replacement");\n        let decoded: PersistedAnchorArtifact =\n            read_artifact_auto(&path, ArtifactKind::Anchor.schema()).expect("reload replacement");\n        assert_eq!(decoded, artifact);\n\n        let file_name = path.file_name().unwrap().to_string_lossy();\n        let prefix = format!(".{file_name}.mimir-stage-");\n        let leftovers = fs::read_dir(directory.path())\n            .expect("read directory")\n            .map(|entry| entry.expect("entry").file_name().to_string_lossy().into_owned())\n            .filter(|name| name.starts_with(&prefix))\n            .collect::<Vec<_>>();\n        assert!(leftovers.is_empty(), "staged writer left temporary files: {leftovers:?}");\n    }\n\n    #[test]\n    fn generic_artifact_serialization_failure_preserves_existing_destination() {\n        let directory = tempdir().expect("tempdir should be created");\n        let path = directory.path().join("artifact.json");\n        let original = b"existing-safe-bytes";\n        fs::write(&path, original).expect("seed destination");\n\n        let artifact = PersistedAnchorArtifact::new(\n            ArtifactHeader::for_kind(ArtifactKind::Anchor, "mimir-io-staged-write-test")\n                .with_metadata(Metadata::from([(\n                    "non_finite",\n                    FieldValue::Float(f64::NAN),\n                )])),\n            AnchorArtifactPayload {\n                id: AnchorId::new("anchor-invalid"),\n                replay_id: ReplayId::new("replay-invalid"),\n                frame_index: FrameIndex::new(8),\n                kind: AnchorKind::Manual,\n                metadata: Metadata::new(),\n            },\n        );\n\n        write_artifact(&path, ArtifactFormat::Json, &artifact)\n            .expect_err("non-finite artifact serialization must fail");\n        assert_eq!(fs::read(&path).expect("read preserved destination"), original);\n    }\n\n'''
text = text.replace(marker, tests + marker, 1)
path.write_text(text, encoding="utf-8", newline="\n")
